name: first_github action code

on:
   pull request:
     branches:
       -main

on:
   push request:
     branches:   
       -main        

env: 
node_version: 18
secrets: ${{secrets.MY_SECRET}}

 main
   jobs:
     my_build:
       runs-on: ubuntu-latest:  
       steps:
         -name: checkout code 
         uses: actions/checkout@v3
         -name: use node version
         uses: actions/setup-node@v3
         with:
         node-version: 17
jobs:
  my_build:
  runs-on: ubuntu-latests
  steps:   
    -name: checkout code
    uses: action/checkout@v3
    -name: use node_version
    uses: action/setup-node@v3
    with:
      node-node_version: ${{env,node_version}}     
 prrpare.html
